[package]
name = "bevy_properties_pane"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_editor_core.workspace = true
bevy_pane_layout.workspace = true
bevy_i-cant-believe-its-not-bsn.workspace = true

[lints]
workspace = true
