[package]
name = "bevy_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_pane_layout.workspace = true
bevy_menu_bar.workspace = true
bevy_editor_styles = { path = "../bevy_editor_styles" }

[lints]
workspace = true
