[package]
name = "getting_started"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_editor = { git = "https://github.com/bevyengine/bevy_editor_prototypes.git" }
rand = "0.8.5"
rand_chacha = "0.3.1"
