[package]
name = "bevy_scene_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_pane_layout.workspace = true
bevy_context_menu.workspace = true
bevy_i-cant-believe-its-not-bsn.workspace = true

[lints]
workspace = true
